delete from opds;
INSERT INTO opds (unit_id, unit_name) VALUES ('416-000','SEKRETARIS DAERAH');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-011','BAGIAN PEMERINTAHAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-012','BAGIAN HUKUM');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-020','BAGIAN PEREKONOMIAN DAN PEMBANGUNAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-021','BAGIAN ADM PEMBANGUNAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-023','BAGIAN ORGANISASI');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-031','BAGIAN PROTOKOL DAN KOMUNIKASI PIMPINAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-032','BAGIAN PERENCANAAN DAN KEUANGAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-033','BAGIAN UMUM');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-034','BAGIAN PBJ');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-050','SEKRETARIAT DPRD');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-060','BADAN PERENCANAAN PEMBANGUNAN DAERAH');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-101','DINAS PENDIDIKAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-102','DINAS KESEHATAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-102-28','UPT Labkesda');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-103','DPU DAN PENATAAN RUANG');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-104','DINAS PERUMAHAN RAKYAT, KAWASAN PERMUKIMAN DAN PERHUBUNGAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-105','SATUAN POLISI PAMONG PRAJA');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-106','DINAS SOSIAL');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-107','DINAS TENAGA KERJA');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-108','DINAS PPKB DAN PEMBERDAYAAN PEREMPUAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-109','DINAS PANGAN DAN PERIKANAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-110','DINAS LINGKUNGAN HIDUP');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-111','DISDUKCAPIL');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-112','DINAS PMD');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-113','DISKOMINFO');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-114','DISKOP UM');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-115','DINAS PENANAMAN MODAL DAN PEKLAYANAN TERPADU SATU PINTU');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-116','DISPARPORA');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-117','DINAS PERPUSTAKAAN DAN KEARSIPAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-118','DINAS PERTANIAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-119','DISPERINDAG');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-201','BAPPEDA');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-202','BAPENDA');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-203','BPKAD');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-204','BKPP');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-205','BPBD');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-206','BAKESBANGPOL');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-207','RSUD PROF. DR. SOEKANDAR');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-208','RSUD RA. BASOENI');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-301','KEC. JATIREJO');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-302','KEC. GONDANG');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-303','KEC. PACET');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-304','KEC. TRAWAS');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-305','KEC. NGORO');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-306','KEC. PUNGGING');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-307','KEC. KUTOREJO');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-308','KEC. MOJOSARI');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-309','KEC. DLANGGU');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-310','KEC. BANGSAL');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-311','KEC. PURI');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-312','KEC. TROWULAN');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-313','KEC. SOOKO');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-314','KEC. GEDEG');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-315','KEC. KEMLAGI');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-316','KEC. JETIS');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-317','KEC. DAWARBLANDONG');
INSERT INTO opds (unit_id, unit_name) VALUES ('416-318','KEC. MOJOANYAR');
INSERT INTO opds (unit_id, unit_name) VALUES ('testing','OPD TESTING');

update opds set unit_id_sidirga=unit_id;